<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            // Page 1
            ['nama_menu' => 'TST (Panas/Dingin)', 'kategori' => 'minuman', 'harga' => 18000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Sanger Panas', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Sanger Dingin', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Coffee BMW', 'kategori' => 'minuman', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Susu Putih Panas', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Susu Putih Dingin', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Susu Coklat Panas', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Susu Coklat Dingin', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Tarik Manual', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Jeruk', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Naga', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Apel', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Pir', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Alpukat', 'kategori' => 'minuman', 'harga' => 13000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Mangga', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Timun', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Wortel', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jus Tomat', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Lemon Tea Panas', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Lemon Tea Dingin', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Syrup Patung', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Syrup Jeruk', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Syrup Leci', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Syrup Melon', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Syrup Marquisa', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Panas', 'kategori' => 'minuman', 'harga' => 7000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Dingin', 'kategori' => 'minuman', 'harga' => 7000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Hijau', 'kategori' => 'minuman', 'harga' => 7000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Cappucino Blend', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Ginseng Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Ulee Kareng Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Luwak Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Cappucino Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Beng Beng Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Good Day Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Chocolatos Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Tarik Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Lemon Tea Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Energen Coklat', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Energen Vanilla', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Energen Kacang Hijau', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Energen Kurma', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Hilo Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],

            // Page 2
            ['nama_menu' => 'Zee Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Kukubima Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Extra Joss Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Hemaviton Jreng Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Jahe Merah Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Creamy Latte Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Coffeemix Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'White Coffee Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Top Coffee Gula Aren Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nutrisari Jeruk Nipis', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nutrisari Lemon Tea', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nutrisari Belimbing', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nutrisari Mangga', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nutrisari Anggur', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nutrisari Kelapa Muda', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Es Teh Poci Panda', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Es Teh Poci Vanilla', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Es Teh Poci Gula Aren', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Es Teh Poci Teh Tarik', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Selasih Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Lasegar Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Adem Sari Sachet', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Botol Sosro', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Teh Pucuk', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Fruit Tea', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Hydro Plus', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Tebs', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Floridina', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Golda', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mount Aqua Sedang', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mount Aqua Gelas', 'kategori' => 'minuman', 'harga' => 1000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Agar Agar Susu', 'kategori' => 'minuman', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Badak Susu', 'kategori' => 'minuman', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Telur 1/2 Matang', 'kategori' => 'minuman', 'harga' => 7000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Pangsit Greget Biasa', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Pangsit Greget Telur', 'kategori' => 'makanan', 'harga' => 18000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Pangsit Greget Bakso', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Pangsit Greget Spesial', 'kategori' => 'makanan', 'harga' => 23000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Pangsit Goreng', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Pangsit Goreng Bakso', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Pangsit Goreng Ayam Kaldu', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Bakso Kaldu', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Bakso Kaldu Ayam', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Tiaw', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],

            // Page 3
            ['nama_menu' => 'Mie Tiaw Bakso', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Chinese', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Chinese Bakso', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Hun', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Hun Bakso', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Balap', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Mie Balap Bakso', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Biasa', 'kategori' => 'makanan', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Telur', 'kategori' => 'makanan', 'harga' => 13000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Bakso', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Ayam', 'kategori' => 'makanan', 'harga' => 18000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Udang', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Spesial', 'kategori' => 'makanan', 'harga' => 22000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Bangladesh', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Indomie Bangladesh Spesial', 'kategori' => 'makanan', 'harga' => 18000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Ayam Geprek Cinta', 'kategori' => 'makanan', 'harga' => 13000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kampung Biasa', 'kategori' => 'makanan', 'harga' => 12000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kampung Telur', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kampung Ayam', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kampung Udang', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kampung Spesial', 'kategori' => 'makanan', 'harga' => 30000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kampung Kasmaran', 'kategori' => 'makanan', 'harga' => 35000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Biasa', 'kategori' => 'makanan', 'harga' => 12000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Telur', 'kategori' => 'makanan', 'harga' => 15000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Ayam', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Udang', 'kategori' => 'makanan', 'harga' => 20000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Spesial', 'kategori' => 'makanan', 'harga' => 30000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Nasi Goreng Kasmaran', 'kategori' => 'makanan', 'harga' => 35000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Dimsum', 'kategori' => 'cemilan', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Burger', 'kategori' => 'cemilan', 'harga' => 10000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Roti Bakar', 'kategori' => 'cemilan', 'harga' => 8000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Donat Paha Ayam', 'kategori' => 'cemilan', 'harga' => 2000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Bakso Goreng', 'kategori' => 'cemilan', 'harga' => 2000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Risol', 'kategori' => 'cemilan', 'harga' => 2000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Tahu Isi', 'kategori' => 'cemilan', 'harga' => 2000, 'status_ketersediaan' => 'tersedia'],
            ['nama_menu' => 'Bakwan Goreng', 'kategori' => 'cemilan', 'harga' => 2000, 'status_ketersediaan' => 'tersedia'],
        ];

        $i = 1;
        foreach ($menus as $item) {
            Menu::create([
                'id_menu'             => 'M' . str_pad($i, 3, '0', STR_PAD_LEFT),
                'nama_menu'           => $item['nama_menu'],
                'kategori'            => $item['kategori'],
                'harga'               => $item['harga'],
                'status_ketersediaan' => $item['status_ketersediaan'],
            ]);
            $i++;
        }
    }
}
